[advisory]
id = "RUSTSEC-0000-0000"
package = "actix-http"
date = "2019-01-28"
title = "Use-after-free in BodyStream due to lack of pinning"
url = "https://github.com/actix/actix-web/issues/1321"
categories = ["memory-corruption"]

description = """
Affected versions of this crate did not require the buffer wrapped in `BodyStream` to be pinned,
but treated it as if it had a fixed location in memory. This may result in a use-after-free.
 
The flaw was corrected by making the trait `MessageBody` require `Unpin`
and making `poll_next()` function accept `Pin<&mut Self>` instead of `&mut self`.
"""

# Versions which include fixes for this vulnerability (mandatory)
[versions]
patched = [">= 2.0.0-alpha.1"]
