[advisory]
id = "RUSTSEC-2020-0011"
package = "plutonium"
date = "2020-04-23"
informational = "notice"
title = "Library exclusively intended to obfuscate code."
url = "https://docs.rs/plutonium/0.2.2/plutonium/"
description = """
This crate allows you to write safe functions with unsafe bodies without the `unsafe` keyword.

The value this adds is questionable, and hides `unsafe` usages from naive analysis.
"""
[versions]
patched = []
