[advisory]
id = "RUSTSEC-0000-0000"
package = "tempdir"
date = "2018-02-13" # date when deprecation was announced on project README
title = "`tempdir` crate has been deprecated; use `tempfile` instead"
informational = "unmaintained"
url = "https://github.com/rust-lang-deprecated/tempdir/pull/46"
description = """
The [`tempdir`](https://crates.io/crates/tempdir) crate has been deprecated
and the functionality is merged into [`tempfile`](https://crates.io/crates/tempfile).
"""

[versions]
unaffected = []
patched = []
