[advisory]
id = "RUSTSEC-2017-0007"
package = "lz4-compress"
title = "lz4-compress is unmaintained"
informational = "unmaintained"
date = "2017-04-17" # last release on crates.io
url = "https://gitlab.redox-os.org/redox-os/tfs/issues/89"
description = """
[According to the developers](https://gitlab.redox-os.org/redox-os/tfs/issues/89) this crate is no longer maintained.

The suggested alternative is [`lz4-compression`](https://crates.io/crates/lz4-compression), a maintained fork of `lz4-compress`.
"""

[versions]
unaffected = []
patched = []
