[advisory]
id = "CVE-2018-1000657"
package = "std"
date = "2018-08-20"
title = "Buffer overflow vulnenrability in VecDeque::reserve()"
description = """
The `std::collections::vec_deque::VecDeque::reserve()` function contains a
buffer overflow vulnerability that can potentially result in arbitrary code
execution.
"""
patched_versions = [">= 1.22.0"]
unaffected_versions = ["< 1.3.0"]
categories = ["code-execution", "denial-of-service"]
url = "https://github.com/rust-lang/rust/issues/44800"
affected_functions = ["std::collections::vec_deque::VecDeque::reserve"]
