[advisory]
id = "RUSTSEC-2019-0035"
alias = "GHSA-mmc9-pwm7-qj5w"
package = "rand_core"
date = "2019-04-19"
informational = "unsound"
title = "Unaligned memory access"
description = """
Affected versions of this crate violated alignment when casting byte slices to
integer slices, resulting in undefined behavior.

The flaw was corrected by Ralf Jung and Diggory Hardy.
"""
url = "https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md#050---2019-06-06"

[affected.functions]
"rand_core::BlockRng::next_u64" = ["< 0.4.2"]
"rand_core::BlockRng::fill_bytes" = ["< 0.4.2"]

[versions]
patched = [">= 0.4.2"]
