[advisory]
id = "RUSTSEC-2019-0017"
package = "once_cell"
date = "2019-09-01"
title = "Panic during initialization of Lazy<T> might trigger undefined behavior"
url = "https://github.com/matklad/once_cell/issues/46"
keywords = ["undefined_behavior"]
description = """
If during the first dereference of Lazy<T> the initialization function panics,
subsequent derefernces will execute `std::hints::unreachable_unchecked`.

Applications with `panic = "abort"` are not affected, as there will be no
subsequent dereferences.
"""

[affected.functions]
"once_cell::unsync::Lazy::force" = ["< 1.0.1, >= 0.2.5"]
"once_cell::unsync::Lazy::deref" = ["< 1.0.1, >= 0.2.5"]
"once_cell::sync::Lazy::force" = ["< 1.0.1, >= 0.2.5"]
"once_cell::sync::Lazy::deref" = ["< 1.0.1, >= 0.2.5"]

[versions]
patched = [">= 1.0.1"]
unaffected = ["< 0.2.5"]
