name: Publish Web

on:
  push:
    branches: main

permissions: {}

jobs:
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for pushing back to the repo
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: gh-pages
          persist-credentials: true # persists the token for git push below

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: admin-cache
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - run: |
          rustsec-admin web .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update gh-pages" || true
          git push || true
