name: Synchronize IDs

on:
  workflow_dispatch:
  schedule:
    # daily run on default "main" branch
    - cron: "30 1 * * *"

permissions: {}

jobs:
  sync-ids:
    name: Synchronize IDs
    runs-on: ubuntu-latest
    permissions:
      contents: write # for create-pull-request
      pull-requests: write # for create-pull-request
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Cache cargo bin
        id: admin-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - name: Synchronize IDs
        id: sync_ids
        run: |
          mkdir -p /tmp/osv
          curl --silent --output /tmp/osv/advisories.zip https://osv-vulnerabilities.storage.googleapis.com/crates.io/all.zip
          unzip -d /tmp/osv -q /tmp/osv/advisories.zip
          rustsec-admin sync --osv /tmp/osv/ .
          message="Synchronize IDs ($(date +%F))"
          echo "commit_message=${message}" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.sync_ids.outputs.commit_message }}
          title: ${{ steps.sync_ids.outputs.commit_message }}
          branch: sync-ids
