name: Validate

on:
  pull_request: {}
  push:
    branches: main

jobs:
  lint:
    name: Lint advisories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo bin
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin
        key: rustsec-admin-v0.8.8

    - name: Install rustsec-admin
      run: |
        VERSION="0.8.8"
        if ! ( rustsec-admin --version | grep -q "$VERSION" ); then
          cargo install rustsec-admin --force --vers "$VERSION"
        fi

    - name: Lint advisories
      run: rustsec-admin lint --skip-namecheck rustdecimal --skip-namecheck vec-const
