name: Validate

on:
  pull_request: {}
  push:
    branches: main

permissions: {}

jobs:
  lint:
    name: Lint advisories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Cache cargo bin
        id: admin-cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-7ed6bee1571768e528a6631400d3b51f37463b29

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 7ed6bee1571768e528a6631400d3b51f37463b29

      - name: Lint advisories
        run: rustsec-admin lint --skip-namecheck rustdecimal,vec-const
