[advisory]
id = "RUSTSEC-2020-0001"
package = "tiny-http"
date = "2020-06-16"
title = "HTTP Request smuggling through malformed Transfer Encoding headers "
url = "https://github.com/tiny-http/tiny-http/issues/173"
categories = ["format-injection"]
keywords = ["http", "request-smuggling"]

description = """
HTTP pipelining issues and request smuggling attacks are possible due to incorrect 
Transfer encoding header parsing.

It is possible conduct HTTP request smuggling attacks (CL:TE/TE:TE) by sending invalid 
Transfer Encoding headers. By manipulating the HTTP response the attacker could poison a web-cache, 
perform an XSS attack, or obtain sensitive information from requests other than their own.
"""

[versions]
patched = []
